-- CREATE DATABASE
CREATE DATABASE ALX_BOOK_STORE;

-- USE DATABASE
USE ALX_BOOK_STORE;

-- AUTHORS TABLE
CREATE TABLE AUTHORS (
    AUTHOR_ID INT PRIMARY KEY AUTO_INCREMENT,
    AUTHOR_NAME VARCHAR(215) NOT NULL
);

-- BOOKS TABLE
CREATE TABLE BOOKS (
    BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
    TITLE VARCHAR(130) NOT NULL,
    AUTHOR_ID INT,
    PRICE DOUBLE,
    PUBLICATION_DATE DATE,
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

-- CUSTOMERS TABLE
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_NAME VARCHAR(215) NOT NULL,
    EMAIL VARCHAR(215),
    ADDRESS TEXT
);

-- ORDERS TABLE
CREATE TABLE ORDERS (
    ORDER_ID INT PRIMARY KEY AUTO_INCREMENT,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    FOREIGN
